artifact_uri: s3://project-ml-college/mlflow-artifacts/0f4a3563cb414e309c1ac28faa8fa25f/artifacts
end_time: 1764591354062
entry_point_name: ''
experiment_id: '922479152663244873'
lifecycle_stage: active
run_id: 0f4a3563cb414e309c1ac28faa8fa25f
run_name: Random Forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1764591349786
status: 3
tags: []
user_id: evaldocunhafilho
