artifact_location: file:///Users/evaldocunhafilho/Documents/Data_Science/ML-College-Project/mlflow/metrics/0
creation_time: 1764591341214
experiment_id: '0'
last_update_time: 1764591341214
lifecycle_stage: active
name: Default
