artifact_uri: s3://project-ml-college/mlflow-artifacts/b9d47857e3da46d8b132b876a5afd319/artifacts
end_time: 1764591367279
entry_point_name: ''
experiment_id: '922479152663244873'
lifecycle_stage: active
run_id: b9d47857e3da46d8b132b876a5afd319
run_name: K-Nearest Neighbors
source_name: ''
source_type: 4
source_version: ''
start_time: 1764591364242
status: 3
tags: []
user_id: evaldocunhafilho
