artifact_uri: s3://project-ml-college/mlflow-artifacts/3fb03d13a05d4ade8ab4a463f6fe5708/artifacts
end_time: 1764591364237
entry_point_name: ''
experiment_id: '922479152663244873'
lifecycle_stage: active
run_id: 3fb03d13a05d4ade8ab4a463f6fe5708
run_name: Gaussian Naive Bayes
source_name: ''
source_type: 4
source_version: ''
start_time: 1764591361221
status: 3
tags: []
user_id: evaldocunhafilho
